// Supabase Client - Auto-generated by Backend Service
// DO NOT import supabase directly for authenticated operations
// Use the useSupabase() hook instead to ensure proper authentication

import { createClient } from '@supabase/supabase-js';

const supabaseUrl = import.meta.env.VITE_SUPABASE_URL;
const supabaseAnonKey = import.meta.env.VITE_SUPABASE_ANON_KEY;
const hasUsableValue = (value) => Boolean(value) && !String(value).includes('your-');

export const isSupabaseConfigured = hasUsableValue(supabaseUrl) && hasUsableValue(supabaseAnonKey);

// Base client - for public/unauthenticated queries only
export const supabase = isSupabaseConfigured ? createClient(supabaseUrl, supabaseAnonKey) : null;

// Factory for authenticated client - used by useSupabase() hook
export function createAuthenticatedClient(accessToken) {
  if (!isSupabaseConfigured || !accessToken) return supabase;

  const client = createClient(supabaseUrl, supabaseAnonKey, {
    global: {
      headers: {
        Authorization: `Bearer ${accessToken}`,
      },
    },
  });

  // Authenticate the realtime WebSocket connection for RLS to work
  client.realtime.setAuth(accessToken);

  return client;
}
